fixes:
  - "src/moveit2/::"

ignore:
  - "*/**/test/*" # ignore package test directories, e.g. moveit_core/robot_trajectory/test
  - "*/test/**/*" # ignore package test directories, e.g. moveit_kinematics/test
  - "**/test_*.*" # ignore files starting with test_ e.g. moveit_core/collision_detection/test/test_all_valid.cpp
  - "**/*_test.*" # ignore files ending   with _test e.g. moveit_planners/trajopt/test/trajectory_test.cpp
