name: add_pr_and_issues
run-name: 
on: [pull_request, issues]
  labels :
    types : [created, edited]
jobs:
  adds_pr_and_issues_automatically:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    permissions : read-all|write-all
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      
