name: Backport
on:
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: Backport
        uses: tibdex/backport@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
