name: Build Dockers (Rolling)

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build_docker:
    strategy:
      matrix:
        env:
          - DOCKERFILE: source
          - DOCKERFILE: ci
          # - DOCKERFILE: ci-testing
          # - DOCKERFILE: release

    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    env:
      ROS_DISTRO: rolling
      IMAGE_ID: ghcr.io/${{ github.repository_owner }}/moveit2
      VERSION: $ROS_DISTRO-${{ matrix.env.DOCKERFILE }}

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: |
          echo Building docker ${{ env.IMAGE_ID }}:${{ env.VERSION }}
          docker build . --build-arg ROS_DISTRO=${{ env.ROS_DISTRO }} --file .docker/${{ matrix.env.DOCKERFILE }}/Dockerfile --tag ${{ env.IMAGE_ID }}:${{ env.VERSION }}

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          docker push ${{ env.IMAGE_ID }}:${{ env.VERSION }}
