name: Docker Lint

on:
  workflow_dispatch:
  push:
    paths:
      - .docker/**
      - .github/workflows/docker_lint.yaml
  pull_request:
    paths:
      - .docker/**
      - .github/workflows/docker_lint.yaml

jobs:
  docker-lint:
    strategy:
      fail-fast: false
      matrix:
        DOCKERFILE_PATH: [ci, ci-testing, release, source]

    name: Lint Dockerfiles
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v2.1.0
=======
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
>>>>>>> 47180f51e (🛠️ Bump hadolint/hadolint-action from 2.1.0 to 3.0.0 (#1713))
        with:
          dockerfile: .docker/${{ matrix.DOCKERFILE_PATH }}/Dockerfile
          config: .docker/.hadolint.yaml
