
# This config uses industrial_ci (https://github.com/ros-industrial/industrial_ci.git).
# For troubleshooting, see readme (https://github.com/ros-industrial/industrial_ci/blob/master/README.rst)

name: BuildAndTest

on: [push, pull_request]

jobs:
  industrial_ci:
    env:
      ROS_DISTRO: foxy
      ROS_REPO: main
      CLANG_TIDY: true
      CCACHE_DIR: /home/runner/.ccache
      BASEDIR: .base
      UPSTREAM_WORKSPACE: moveit2.repos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ env.ROS_DISTRO }}-${{ env.ROS_REPO }}-${{ github.sha }}
          restore-keys: |
            ccache-${{ env.ROS_DISTRO }}-${{ env.ROS_REPO }}
      - uses: 'Briancbn/industrial_ci@pr-coverage'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: test-results
          path: ${{ env.BASEDIR }}/target_ws/**/test_results/**/*.xml
      - uses: codecov/codecov-action@v1
