name: Add new issues and pull-requests to project

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  issues: read
  pull-requests: read
  repository-projects: write

jobs:
  add-to-project:
    name: Add new issues and pull-requests to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@0.4.1
        with:
          project-url: https://github.com/orgs/ros-planning/projects/5
          github-token: ${{ secrets.GITHUB_TOKEN }}
